<definitions xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ws="http://IcelandicOnlineBanking/2005/12/01" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ct="http://IcelandicOnlineBanking/2005/12/01/CommonTypes" xmlns:st="http://IcelandicOnlineBanking/2005/12/01/StatementTypes" xmlns:pt="http://IcelandicOnlineBanking/2005/12/01/PaymentTypes" targetNamespace="http://IcelandicOnlineBanking/2005/12/01">
	<import namespace="http://IcelandicOnlineBanking/2005/12/01/Payments" location="IcelandicOnlineBankingPayments.wsdl"/>	
	<import namespace="http://IcelandicOnlineBanking/2005/12/01/Statements" location="IcelandicOnlineBankingStatements.wsdl"/>
	<import namespace="http://IcelandicOnlineBanking/2005/12/01/Claims" location="IcelandicOnlineBankingClaims.wsdl"/>
</definitions>